# Build stage
FROM node:20-alpine AS build
WORKDIR /app

COPY backend/package*.json ./
RUN npm ci


COPY backend/tsconfig.json ./
COPY backend/src ./src

RUN npm run build

# Runtime stage
FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=production

COPY backend/package*.json ./
RUN npm ci --omit=dev

COPY --from=build /app/dist ./dist
COPY backend/src/proto ./dist/proto

EXPOSE 50051

CMD ["node", "dist/modules/auth/auth-module.js"]
